name: jalali_calendar
description: Calendar , Datepicker and Date Convertor For Persian Date(Jalali/Shamsi date) with holiday for Android and Ios
version: 1.0.3+1
homepage: https://github.com/irdeveloper89/jalali_calendar

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  persian_date:
    git: https://github.com/TalebRafiepour/PersianDate.git
  flutter:
    sdk: flutter
  jiffy: ^4.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter